import type { RaffleItem } from '../types';

export const initialRaffleItemsData: RaffleItem[] = [
  {
    id: 'grid_0_499',
    raffleType: 'grid',
    name: 'Gran Rifa Pukatu 000-499',
    imageUrl: 'https://picsum.photos/seed/gridpukatuA/300/120',
    ticketPurchaseLink: '#',
    ticketCheckLink: '#',
    date: '30/AGOSTO/2024',
    progressPercentage: 10,
    targetDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    administratorWhatsApp: '584120000000',
    managedByAdminId: 'roble',
    ticketCost: 2,
    gridNumbersTotal: 500,
    gridStartNumber: 0,
    prizeDetails: [
      "1er. Premio: PlayStation 5",
      "2do. Premio: Silla Gamer",
    ],
    soldNumbers: [0, 10, 25, 50, 100, 123, 250, 300, 499],
    raffleTitle: "RIFA PUKATU (000-499)",
    raffleSubtitle: "PREMIOS INCREÍBLES",
    callToAction: "¡ELIGE TU NÚMERO!",
    day: '30',
    month: 'Agosto',
    isFeatured: true,
    description: "Participa en la rifa especial por una PS5. Números del 000 al 499.",
    conditions: "Sorteo válido a nivel nacional. Premios no transferibles.",
  },
  {
    id: 'grid_500_999',
    raffleType: 'grid',
    name: 'Gran Rifa Pukatu 500-999',
    imageUrl: 'https://picsum.photos/seed/gridpukatuB/300/120',
    ticketPurchaseLink: '#',
    ticketCheckLink: '#',
    date: '30/AGOSTO/2024',
    progressPercentage: 5,
    targetDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    administratorWhatsApp: '584120000000',
    managedByAdminId: 'roble',
    ticketCost: 2,
    gridNumbersTotal: 500,
    gridStartNumber: 500,
    prizeDetails: [
        "1er. Premio: TV 55 pulgadas 4K",
        "2do. Premio: Barra de Sonido",
    ],
    soldNumbers: [500, 555, 678, 800, 999],
    raffleTitle: "RIFA PUKATU (500-999)",
    raffleSubtitle: "MÁS OPORTUNIDADES",
    callToAction: "¡NO TE QUEDES FUERA!",
    day: '30',
    month: 'Agosto',
    isFeatured: true,
    description: "Participa en la rifa especial por un TV 4K. Números del 500 al 999.",
    conditions: "Sorteo válido a nivel nacional. Premios no transferibles.",
  },
];